# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Flux Framework
tagline: A flexible framework for resource management customized for your HPC site
description: Flux Framework
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flux-framework.org" # the base hostname & protocol for your site, e.g. http://example.com
image: /assets/images/logo-2x.png
domain: flux-framework.org

# Build settings
markdown: kramdown
repository: flux-framework/flux-framework.github.io
github: [metadata]

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - src
  - .jekyll-cache
  - env

twitter-img: /assets/images/Flux-logo-full.png
twitter: FluxFramework
twitter_card: summary

# Collections
collections:
    events:
      output: false
      permalink: /:collection/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      is_post: true 

# Post pagination
paginate: 5
paginate_path: "/news/page:num/"
plugins:
  - jekyll-feed