markdown: kramdown
kramdown:
  input: GFM

permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/flux-framework

collections:
  docs:
    output: true

name: The Flux Resource Manager Framework
description: Flexible, Scalable, Customizable Framework enabling site-customized Resource Management for HPC
url: https://flux-framework.github.io

theme: jekyll-theme-cayman