name: flux-framework docs

on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches-ignore:
    - main
    - master

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Spelling
      uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
      with:
        files: ./README.md ./_posts
